# Generated by Django 2.1.7 on 2019-04-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190418_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
            ],
            options={
                'verbose_name': 'Delivery Address Routing',
                'verbose_name_plural': 'Delivery Addresses Routing',
                'proxy': True,
                'indexes': [],
            },
            bases=('order.order',),
        ),
    ]
